// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finalPCS.Data;

#nullable disable

namespace finalPCS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230207064327_intialmigration")]
    partial class intialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("finalPCS.Models.Emp_Qualification", b =>
                {
                    b.Property<int>("Employee_id")
                        .HasColumnType("int");

                    b.Property<int>("Q_id")
                        .HasColumnType("int");

                    b.Property<float>("Marks")
                        .HasColumnType("real");

                    b.HasKey("Employee_id", "Q_id");

                    b.HasIndex("Q_id");

                    b.ToTable("Emp_Qualifications");
                });

            modelBuilder.Entity("finalPCS.Models.Employee", b =>
                {
                    b.Property<int>("Employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Employee_id"), 1L, 1);

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Salary")
                        .HasColumnType("real");

                    b.HasKey("Employee_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("finalPCS.Models.Qualification_List", b =>
                {
                    b.Property<int>("Q_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Q_id"), 1L, 1);

                    b.Property<string>("Q_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Q_id");

                    b.ToTable("Qualification_Lists");
                });

            modelBuilder.Entity("finalPCS.Models.Emp_Qualification", b =>
                {
                    b.HasOne("finalPCS.Models.Employee", "Employee")
                        .WithMany("Emp_Qualifications")
                        .HasForeignKey("Employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("finalPCS.Models.Qualification_List", "Qualification_List")
                        .WithMany("Emp_Qualifications")
                        .HasForeignKey("Q_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Qualification_List");
                });

            modelBuilder.Entity("finalPCS.Models.Employee", b =>
                {
                    b.Navigation("Emp_Qualifications");
                });

            modelBuilder.Entity("finalPCS.Models.Qualification_List", b =>
                {
                    b.Navigation("Emp_Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
